insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("aaaaaaaaaaaaaaaaasdfghjkjk" , "Closed", 14, 59, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("the quick brown fox jumped over the lazy dog" , "Changed Operating Hours", 50, 22, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("what is this" , "Others", 57, 69, 1, 70);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("wake up get up get out there" , "Closed", 44, 98, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("the quick brown fox jumped over the lazy dog" , "Others", 46, 60, 1, 85);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("what is this" , "Closed", 89, 4, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("lorem ipsum dolor sit amet" , "Others", 48, 3, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("aaaaaaaaaaaaaaaaasdfghjkjk" , "Changed Location", 28, 26, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("the quick brown fox jumped over the lazy dog" , "Changed Location", 39, 38, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("lorem ipsum dolor sit amet" , "Changed Operating Hours", 43, 53, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("aaaaaaaaaaaaaaaaasdfghjkjk" , "Others", 85, 26, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("this is unfair" , "Changed Operating Hours", 69, 44, 1, 85);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("aaaaaaaaaaaaaaaaasdfghjkjk" , "Changed Location", 42, 35, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("aaaaaaaaaaaaaaaaasdfghjkjk" , "Closed", 50, 84, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("lorem ipsum dolor sit amet" , "Closed", 62, 17, 1, 19);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("wake up get up get out there" , "Changed Location", 50, 92, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("what is this" , "Changed Location", 29, 79, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("the quick brown fox jumped over the lazy dog" , "Others", 70, 19, 1, 20);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("aaaaaaaaaaaaaaaaasdfghjkjk" , "Changed Operating Hours", 74, 43, 1, 2);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("wake up get up get out there" , "Changed Operating Hours", 67, 100, 1, 70);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("the quick brown fox jumped over the lazy dog" , "Changed Operating Hours", 33, 86, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("the quick brown fox jumped over the lazy dog" , "Others", 24, 61, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("this is unfair" , "Others", 37, 69, 1, 54);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("wake up get up get out there" , "Changed Operating Hours", 49, 3, 1, 42);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("aaaaaaaaaaaaaaaaasdfghjkjk" , "Changed Operating Hours", 33, 34, 1, 42);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("wake up get up get out there" , "Changed Operating Hours", 51, 44, 1, 85);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("what is this" , "Closed", 40, 11, 1, 42);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("the quick brown fox jumped over the lazy dog" , "Changed Operating Hours", 8, 12, 1, 77);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("aaaaaaaaaaaaaaaaasdfghjkjk" , "Changed Location", 1, 90, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("wake up get up get out there" , "Closed", 53, 87, 1, 20);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("aaaaaaaaaaaaaaaaasdfghjkjk" , "Closed", 65, 74, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("what is this" , "Others", 21, 51, 1, 2);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("the quick brown fox jumped over the lazy dog" , "Changed Operating Hours", 7, 50, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("what is this" , "Changed Location", 48, 74, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("wake up get up get out there" , "Others", 74, 27, 1, 13);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("lorem ipsum dolor sit amet" , "Others", 83, 83, 1, 13);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("aaaaaaaaaaaaaaaaasdfghjkjk" , "Others", 6, 81, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("wake up get up get out there" , "Changed Location", 14, 86, 1, 13);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("what is this" , "Changed Location", 6, 54, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("lorem ipsum dolor sit amet" , "Changed Operating Hours", 62, 51, 1, 71);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("the quick brown fox jumped over the lazy dog" , "Changed Location", 71, 27, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("this is unfair" , "Closed", 65, 16, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("what is this" , "Changed Operating Hours", 21, 20, 1, 89);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("lorem ipsum dolor sit amet" , "Changed Operating Hours", 94, 35, 1, 23);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("aaaaaaaaaaaaaaaaasdfghjkjk" , "Others", 23, 16, 1, 58);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("wake up get up get out there" , "Changed Location", 80, 88, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("what is this" , "Changed Operating Hours", 96, 80, 1, 80);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("aaaaaaaaaaaaaaaaasdfghjkjk" , "Changed Location", 37, 16, 1, 54);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("the quick brown fox jumped over the lazy dog" , "Changed Operating Hours", 52, 55, 1, 2);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("the quick brown fox jumped over the lazy dog" , "Others", 74, 35, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("wake up get up get out there" , "Changed Operating Hours", 76, 74, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("aaaaaaaaaaaaaaaaasdfghjkjk" , "Others", 92, 72, 1, 2);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("the quick brown fox jumped over the lazy dog" , "Changed Location", 95, 40, 1, 54);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("aaaaaaaaaaaaaaaaasdfghjkjk" , "Others", 3, 76, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("lorem ipsum dolor sit amet" , "Others", 38, 69, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("lorem ipsum dolor sit amet" , "Closed", 63, 91, 1, 42);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("the quick brown fox jumped over the lazy dog" , "Others", 31, 77, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("wake up get up get out there" , "Closed", 60, 95, 1, 58);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("what is this" , "Others", 17, 21, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("aaaaaaaaaaaaaaaaasdfghjkjk" , "Closed", 5, 17, 1, 52);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("wake up get up get out there" , "Closed", 15, 30, 1, 85);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("the quick brown fox jumped over the lazy dog" , "Changed Operating Hours", 41, 100, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("wake up get up get out there" , "Others", 44, 87, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("the quick brown fox jumped over the lazy dog" , "Others", 72, 86, 1, 99);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("lorem ipsum dolor sit amet" , "Changed Location", 42, 34, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("the quick brown fox jumped over the lazy dog" , "Closed", 73, 80, 1, 99);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("wake up get up get out there" , "Others", 62, 20, 1, 23);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("aaaaaaaaaaaaaaaaasdfghjkjk" , "Changed Operating Hours", 30, 75, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("what is this" , "Closed", 46, 62, 1, 85);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("what is this" , "Closed", 9, 32, 1, 32);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("this is unfair" , "Changed Operating Hours", 27, 72, 1, 32);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("wake up get up get out there" , "Closed", 58, 60, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("lorem ipsum dolor sit amet" , "Changed Operating Hours", 34, 3, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("this is unfair" , "Changed Operating Hours", 11, 43, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("what is this" , "Changed Location", 72, 100, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("what is this" , "Others", 13, 45, 1, 44);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("what is this" , "Changed Operating Hours", 58, 62, 1, 80);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("this is unfair" , "Others", 82, 75, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("the quick brown fox jumped over the lazy dog" , "Changed Location", 86, 26, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("aaaaaaaaaaaaaaaaasdfghjkjk" , "Closed", 6, 86, 1, 20);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("this is unfair" , "Changed Location", 59, 25, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("wake up get up get out there" , "Changed Operating Hours", 73, 71, 1, 42);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("lorem ipsum dolor sit amet" , "Others", 30, 70, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("this is unfair" , "Others", 2, 75, 1, 70);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("what is this" , "Changed Location", 63, 81, 1, 71);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("what is this" , "Others", 67, 75, 1, 48);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("the quick brown fox jumped over the lazy dog" , "Others", 17, 39, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("wake up get up get out there" , "Changed Location", 80, 28, 1, 17);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("lorem ipsum dolor sit amet" , "Closed", 36, 12, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("the quick brown fox jumped over the lazy dog" , "Others", 7, 61, 1, 23);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("wake up get up get out there" , "Changed Location", 61, 42, 1, 54);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("wake up get up get out there" , "Changed Operating Hours", 35, 83, 1, 32);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("aaaaaaaaaaaaaaaaasdfghjkjk" , "Changed Location", 52, 87, 1, 42);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("lorem ipsum dolor sit amet" , "Changed Location", 99, 83, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("the quick brown fox jumped over the lazy dog" , "Changed Operating Hours", 52, 34, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("wake up get up get out there" , "Changed Operating Hours", 84, 71, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("the quick brown fox jumped over the lazy dog" , "Others", 84, 40, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved) values ("wake up get up get out there" , "Others", 50, 52, 0);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("the quick brown fox jumped over the lazy dog" , "Changed Location", 31, 87, 1, 54);
insert into report(report_details, report_category, restaurant_id, reported_by, is_resolved, resolved_by) values ("what is this" , "Changed Operating Hours", 28, 58, 1, 58);
